<?php declare(strict_types=1);

use Liliana\OA\UI\SwaggerTemplate;

/** @var SwaggerTemplate $template */
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $template->title ?></title>

    <?php require __DIR__ . "/styles.phtml"; ?>
</head>
<body>
    <div id="swagger-root"></div>

    <?php require __DIR__ . "/scripts.phtml"; ?>
</body>
</html>